/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as TranscriptRouteImport } from './routes/transcript'
import { Route as WorkRouteImport } from './routes/work'
import { Route as DocSlugRouteImport } from './routes/doc.$slug'
import { Route as ApiPublicFundingRouteImport } from './routes/api/public/funding'
import { Route as ApiPublicPublishRouteImport } from './routes/api/public/publish'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSlugRoute = DocSlugRouteImport.update({
  id: '/doc/$slug',
  path: '/doc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFundingRoute = ApiPublicFundingRouteImport.update({
  id: '/api/public/funding',
  path: '/api/public/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublishRoute = ApiPublicPublishRouteImport.update({
  id: '/api/public/publish',
  path: '/api/public/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/transcript': typeof TranscriptRoute
  '/work': typeof WorkRoute
  '/doc/$slug': typeof DocSlugRoute
  '/api/public/funding': typeof ApiPublicFundingRoute
  '/api/public/publish': typeof ApiPublicPublishRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/transcript': typeof TranscriptRoute
  '/work': typeof WorkRoute
  '/doc/$slug': typeof DocSlugRoute
  '/api/public/funding': typeof ApiPublicFundingRoute
  '/api/public/publish': typeof ApiPublicPublishRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/transcript': typeof TranscriptRoute
  '/work': typeof WorkRoute
  '/doc/$slug': typeof DocSlugRoute
  '/api/public/funding': typeof ApiPublicFundingRoute
  '/api/public/publish': typeof ApiPublicPublishRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate'
    | '/transcript'
    | '/work'
    | '/doc/$slug'
    | '/api/public/funding'
    | '/api/public/publish'
    | '/api/public/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/transcript'
    | '/work'
    | '/doc/$slug'
    | '/api/public/funding'
    | '/api/public/publish'
    | '/api/public/tick'
  id:
    | '__root__'
    | '/'
    | '/donate'
    | '/transcript'
    | '/work'
    | '/doc/$slug'
    | '/api/public/funding'
    | '/api/public/publish'
    | '/api/public/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  TranscriptRoute: typeof TranscriptRoute
  WorkRoute: typeof WorkRoute
  DocSlugRoute: typeof DocSlugRoute
  ApiPublicFundingRoute: typeof ApiPublicFundingRoute
  ApiPublicPublishRoute: typeof ApiPublicPublishRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$slug': {
      id: '/doc/$slug'
      path: '/doc/$slug'
      fullPath: '/doc/$slug'
      preLoaderRoute: typeof DocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/funding': {
      id: '/api/public/funding'
      path: '/api/public/funding'
      fullPath: '/api/public/funding'
      preLoaderRoute: typeof ApiPublicFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publish': {
      id: '/api/public/publish'
      path: '/api/public/publish'
      fullPath: '/api/public/publish'
      preLoaderRoute: typeof ApiPublicPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  TranscriptRoute: TranscriptRoute,
  WorkRoute: WorkRoute,
  DocSlugRoute: DocSlugRoute,
  ApiPublicFundingRoute: ApiPublicFundingRoute,
  ApiPublicPublishRoute: ApiPublicPublishRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
